name:                bowbot
version:             0.1.0.0
github:              "Gregory1234/bowbot"
author:              "Greg C"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Gregory1234/bowbot#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- text
- containers
- aeson
- http-conduit
- bytestring
- unordered-containers
- time
- stm
- async
- http-client-tls
- split
- mtl
- deepseq
- mysql-haskell
- stringsearch
- hashable
- data-has
- text-show
- mime-mail
- zlib
- io-streams
- binary
# only for mysql quasi quoter
- template-haskell
- parsec

library:
  source-dirs: src

language: GHC2021

default-extensions:
- LambdaCase
- DerivingVia
- RecordWildCards
- OverloadedStrings
- DataKinds
- ViewPatterns

ghc-options:
- -Wall
- -O2

executables:
  bowbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bowbot